#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Application;
use Devbanana\OptionCalculator\Command\ListExpirationsCommand;
use Devbanana\OptionCalculator\Command\GetQuoteCommand;

$dotenv = new Dotenv();
$dotenv->loadEnv(__DIR__.'/.env');

$application = new Application('Option Calculator');

$application->addCommands([
    new ListExpirationsCommand(),
    new GetQuoteCommand(),
]);

$application->run();
