#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Application;
use Devbanana\OptionCalculator\Command\ListExpirationsCommand;
use Devbanana\OptionCalculator\Command\GetQuoteCommand;
use Devbanana\OptionCalculator\Command\ChainCommand;
use Devbanana\OptionCalculator\Command\AccountPositionsCommand;
use Devbanana\OptionCalculator\Command\TradeCreateCommand;
use Devbanana\OptionCalculator\Command\TradeModifyCommand;
use Devbanana\OptionCalculator\Command\TradeStatusCommand;
use Devbanana\OptionCalculator\Command\CalculateRsiCommand;
use Devbanana\OptionCalculator\Command\CalculateAdxCommand;
use Devbanana\OptionCalculator\Command\CalculateExpectedMoveCommand;

$dotenv = new Dotenv();
$dotenv->loadEnv(__DIR__.'/.env');

$application = new Application('Option Calculator');

$application->addCommands([
    new ListExpirationsCommand(),
    new GetQuoteCommand(),
    new ChainCommand(),
    new AccountPositionsCommand(),
    new TradeCreateCommand(),
    new TradeModifyCommand(),
    new TradeStatusCommand(),
    new CalculateRsiCommand(),
    new CalculateAdxCommand(),
    new CalculateExpectedMoveCommand(),
]);

$application->run();
